# Generated by Django 5.2 on 2025-05-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                default="stripe",
                max_length=10,
            ),
        ),
    ]
