name: Deploy to Server with Docker and Poetry

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false
      - name: Install Dependencies and Run Tests
        run: |
          poetry install --no-interaction --no-ansi
          poetry run python manage.py test  # Запуск тестов с помощью Poetry
      - name: Build Static
        run: |
          poetry run python manage.py collectstatic --noinput  # Собираем статику с помощью Poetry

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.repository_owner == github.actor
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          scope: ${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build_image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Logging in to server"
            cd /home/django/your_project_directory # Замените на ваш путь

            # Остановите и удалите существующий контейнер
            docker stop myproject_container || true
            docker rm myproject_container || true

            # Pull image
            docker pull ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

            # Запустите новый контейнер
            docker run -d --name myproject_container \
              -p 8000:8000 \
              -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
              -e DJANGO_DATABASE_NAME="${{ secrets.DJANGO_DATABASE_NAME }}" \
              -e DJANGO_DATABASE_USER="${{ secrets.DJANGO_DATABASE_USER }}" \
              -e DJANGO_DATABASE_PASSWORD="${{ secrets.DJANGO_DATABASE_PASSWORD }}" \
              -e DJANGO_DATABASE_HOST="${{ secrets.SSH_HOST }}" # Use SSH_HOST for DB access
              -e DJANGO_DEBUG=False # Enable debug on dev only
              ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
